# Generated by Django 3.2.16 on 2022-10-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221016_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='image_lists',
            field=models.ManyToManyField(related_name='image_lists', to='core.Image_File'),
        ),
    ]
