# Generated by Django 3.2.16 on 2022-10-17 02:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patients_image_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_file',
            name='image',
            field=models.FileField(null=True, upload_to=core.models.patients_image_file_path),
        ),
    ]
