# Generated by Django 3.2.16 on 2022-10-18 08:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_image_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_file',
            name='image',
            field=models.FileField(null=True, upload_to=core.models.patients_image_file_path),
        ),
        migrations.AlterField(
            model_name='patients',
            name='image_lists',
            field=models.ManyToManyField(to='core.Image_File'),
        ),
    ]
